BACKEND_URL: http://localhost:8080
FRONTEND_URL: http://localhost:3000
AUTH_KEY: auth
HEADER_KEYS:
  auth_logout: x-auth-logout
FRONTEND_ROUTES:
  verify_signup: /welcome
  verify_magic_link: /verify-magic-link
  galleries: /galleries
SCOPE_NAME_MAPPING:
  admin: 1
  user.read: 2
  user.write: 3
VISIBILITY_LEVEL_NAME_MAPPING:
  public: 1
  private: 2
PERMISSION_LEVEL_NAME_MAPPING:
  editor: 2
  viewer: 1
USER_ROLE_NAME_MAPPING:
  admin: 2
  user: 1
USER_ROLE_SCOPES:
  admin:
    - admin
    - user.read
    - user.write
  user:
    - user.read
    - user.write
OTP_LENGTH: 6
GOOGLE_CLIENT_ID: abcdef.apps.googleusercontent.com
